---
# tasks file for launch_vpc

- name: create a cloudformation stack
  amazon.aws.cloudformation:
    stack_name: "{{ ec2_name_prefix }}"
    state: "present"
    region: "us-east-1"
    disable_rollback: true
    template_body: "{{ vpc_template }}"
    tags:
      Stack: "{{ ec2_name_prefix }}"